---
  - service:
       name: glusterd
       state: restarted
       enabled: yes
  - name: Create bricks
    file:
       path: /{{mount_point_1}}
       state: directory
       mode: 0775
  - name: Create a PV disk
    lvg:
       pvs: "{{disk_name}}"
       vg: "{{volume_group}}"

  - name: create Thinpool
    lvol:
      vg: "{{volume_group}}"
      thinpool: "{{pool}}"
      size: "{{pool_size}}"
    notify:
        - restart glusterd



  - name: Create lvm 1
    lvol:
       vg: "{{volume_group}}"
       lv: "{{logical_volume}}"
       thinpool: "{{pool}}"
       size: "{{lv_size}}"

  - name: Create a xfs filesystem on lv1
    filesystem:
      fstype: xfs
      dev: /dev/{{ volume_group }}/{{ logical_volume }}
  - name: mount logical volume
    mount:
      path: /{{mount_point_1}}
      src: /dev/{{ volume_group }}/{{ logical_volume }}
      fstype: xfs
      state: mounted
      backup: no
      boot: yes
  - name: Create subdirectory
    file:
       path: /{{ mount_point_1}}/{{ sub_dir }}
       state: directory
       mode: 0775

