---
  - service:
       name: glusterd
       state: restarted
       enabled: yes
  - name: Create bricks
    file:
       path: /{{mount_point_1}}
       state: directory
       mode: 0775
  - name: Create a PV disk
    lvg:
       pvs: "{{disk_name}}"
       vg: "{{volume_group_1}}"

  - name: create Thinpool
    lvol:
      vg: "{{volume_group_1}}"
      thinpool: "{{pool_1}}"
      size: "{{pool_size}}"
    notify:
        - restart glusterd



  - name: Create lvm 1
    lvol:
       vg: "{{volume_group_1}}"
       lv: "{{logical_volume_1}}"
       thinpool: "{{pool_1}}"
       size: "{{size1}}"

  - name: Create a xfs filesystem on lv1
    filesystem:
      fstype: xfs
      dev: /dev/{{ volume_group_1 }}/{{ logical_volume_1 }}
  - name: mount lv1
    mount:
      path: /{{mount_point_1}}
      src: /dev/{{ volume_group_1 }}/{{ logical_volume_1 }}
      fstype: xfs
      state: mounted
      backup: no
      boot: yes
  - name: Create subdirectory
    file:
       path: /{{mount_point_1}}/{{ sub_dir_1 }}
       state: directory
       mode: 0775

