---
- hosts: dev
  tasks:
  - name: Restart service gluster and enabled, in all cases
    service:
       name: glusterd
       state: restarted
       enabled: yes
  - name: Create a trusted storage pool
    gluster_peer:
       state: present
       nodes: 192.168.122.120
  - name: Create bricks
    file:
       path: /brick1/one
       state: directory
       mode: 0775
    file:
       path: /brick2/one
       state: directory
       mode: 0775
    file:
       path: /brick3/one
       state: directory
       mode: 0775
#################### logical volume
#
  - name: Create a PV disk 
    lvg:
       pvs: /dev/sdb
       vg: vg1
#  - name: Create a logical pool
#    lvol:
#       vg: vg1
#       lv: pool
#       size: 100%FREE

  - name: create Thinpool
    lvol:
      vg: vg1
      thinpool: pool
      size: 8g
  
  - name: Create lvm 1
    lvol:
       vg: vg1
       lv: lv1
       thinpool: pool
       size: 1g
  - name: Create lvm 2
    lvol:
       vg: vg1
       lv: lv2
       thinpool: pool
       size: 1g
  - name: Create lvm 3
    lvol:
       vg: vg1
       lv: lv3
       thinpool: pool
       size: 1g
  - name: Create a exf filesystem on lv1
    filesystem:
      fstype: xfs
      dev: /dev/vg1/lv1
  - name: Create a exf filesystem on lv2
    filesystem:
      fstype: xfs
      dev: /dev/vg1/lv2
  - name: Create a exf filesystem on lv3
    filesystem:
      fstype: xfs
      dev: /dev/vg1/lv3

########################## Mounting bricks


  - name: mount 
    mount:
      path: /brick1
      src: /dev/vg1/lv1
      fstype: xfs
      state: mounted
      backup: no
      boot: yes
  
  - name: mount 
    mount:
      path: /brick2
      src: /dev/vg1/lv2
      fstype: xfs
      state: mounted
      backup: no
      boot: yes

  - name: mount 
    mount:
      path: /brick3
      src: /dev/vg1/lv3
      fstype: xfs
      state: mounted
      backup: no
      boot: yes
########################## Creating gluster Volume


  - name: Create volume
    gluster_volume:
      state: present
      name: Vol1
      bricks: /brick1/one,/brick2/one,/brick3/one
      replicas: 0
      cluster:
        - 192.168.122.120
    run_once: true


  - name: start gluster volume
    gluster_volume:
      state: started
      name: Vol1
  
  - name: Create dir inside mnt point
    file:
      path: /mnt/gluster_vol
      state: directory
      mode: 0775
  
  - name: Mounting Vol
    mount:
      src: 192.168.122.120:/Vol1
      path: /mnt/gluster_vol
      fstype: glusterfs
      opts: _netdev
      state: mounted
      backup: no
      boot: yes

